// Built-in question bank. Used when a server hasn't added any of its own,
// so QOTD produces something interesting the moment it's switched on.
// Tone: light, low-stakes, made for friend groups & gaming squads — the
// kind of prompt that actually gets replies, not a job interview.
export const DEFAULT_QUESTIONS: readonly string[] = [
  'What game have you sunk the most hours into, and zero regrets?',
  "What's a movie or show you'll defend to the death even though it's objectively kind of bad?",
  'If you could instantly master one skill, what would it be?',
  "What's the best meal you've had recently?",
  'Coffee, tea, energy drink, or pure spite — what fuels you?',
  "What's a hill you'll die on that has nothing to do with anything important?",
  'If our server had a mascot, what should it be?',
  "What's the last thing that genuinely made you laugh out loud?",
  'Worst game you ever bought full price for?',
  "What's a small thing that instantly improves your day?",
  'If you could respec your real-life skill tree, what goes first?',
  "What's your comfort game — the one you go back to when nothing else hits?",
  'Cats, dogs, or some chaotic third option?',
  "What's the most useless talent you have?",
  'If you had to delete one app from your phone forever, which one?',
  "What's a hot take you have about food?",
  "What's the best purchase you've made under $20?",
  'Early bird or night owl, and be honest?',
  "What fictional place would you actually want to live in?",
  "What's a song you can't skip no matter what?",
  'If you could add one feature to this server, what would it be?',
  "What's the weirdest thing you believed as a kid?",
  'Pineapple on pizza: crime or genius?',
  "What's a game you wish you could play again for the first time?",
  "What's your go-to order at a place you visit too often?",
  'If you were a boss in a video game, what would your one-shot attack be?',
  "What's something you're irrationally good at?",
  "What's the best advice you've ever gotten in a single sentence?",
  'Which one of us would survive longest in a zombie apocalypse, and why is it not you?',
  "What's a trend you completely missed and never understood?",
];
